spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5431/catalizator
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5431/catalizator
    password: postgres
    user: postgres